#!/usr/bin/env python3
import random, array, sys, argparse

def valid_input(output, lower, upper):
    verified = False
    while verified == False:
        try:
            print(output)
            verified_int = int(input())
            if verified_int < lower:
                print("Please enter a number bigger than", lower)
                continue
            elif verified_int > upper:
                print("Please enter a number smaller than", upper)
                continue
            else:
                verified = True
        except:
            print("Please enter a number")
    return verified_int

def print_civs(civs):
    print("")
    for i in range(len(civs)):
        print('({})'.format(i+1), civs[i], end='')
        if i >= len(civs) - 1:
            print("")
        else:
            print(", ", end='')
    print("")

def pick_and_remove(array):
    n = random.randrange(0, len(array))
    print(array[n])
    array.pop(n)

def main():
    all_civs = ["American", "Arabian", "Assyrian", "Austrian", "Aztec", "Babylonian", "Brazilian", "Byzantine", "Carthaginian", "Celtic", "Chinese", "Danish", "Dutch", "Egyptian", "English", "Ethiopian", "French", "German", "Greek", "Hunnic", "Incan", "Indian", "Indonesian", "Iroquois", "Japanese", "Korean", "Mayan", "Mongolian", "Moroccan", "Ottoman", "Persian", "Polish", "Polynesian", "Portuguese", "Roman", "Russian", "Shoshone", "Siamese", "Songhai", "Spanish", "Swedish", "Venetian", "Zulu"]
    
    player_count = valid_input("How many players are there? (1-12)", 1, 12)
    civs_per_player = valid_input("How many civilisations should each player choose from? (1-3)", 1, 3)

    banned_done = False
    while banned_done == False:
        print_civs(all_civs)
        civ_to_ban = valid_input("Input the number of the civilisation you would like to remove, or \"0\" to exit this menu", 0, len(all_civs))
        if civ_to_ban == 0:
            banned_done = True
        else:
            civ_to_ban = civ_to_ban - 1
            print("Removing", all_civs[civ_to_ban] + "...")
            all_civs.pop(civ_to_ban)

    for i in range(player_count):
        print ("\nPlayer", i+1)
        temp_civs = all_civs
        for j in range(civs_per_player):
            pick_and_remove(temp_civs)

main()
